/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
Mdajx10AudioProcessor::Mdajx10AudioProcessor()
{
}

Mdajx10AudioProcessor::~Mdajx10AudioProcessor()
{
}

//==============================================================================
const String Mdajx10AudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int Mdajx10AudioProcessor::getNumParameters()
{
    return 0;
}

float Mdajx10AudioProcessor::getParameter (int index)
{
    return 0.0f;
}

void Mdajx10AudioProcessor::setParameter (int index, float newValue)
{
}

const String Mdajx10AudioProcessor::getParameterName (int index)
{
    return String();
}

const String Mdajx10AudioProcessor::getParameterText (int index)
{
    return String();
}

const String Mdajx10AudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String Mdajx10AudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool Mdajx10AudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool Mdajx10AudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

bool Mdajx10AudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool Mdajx10AudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool Mdajx10AudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double Mdajx10AudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int Mdajx10AudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int Mdajx10AudioProcessor::getCurrentProgram()
{
    return 0;
}

void Mdajx10AudioProcessor::setCurrentProgram (int index)
{
}

const String Mdajx10AudioProcessor::getProgramName (int index)
{
    return String();
}

void Mdajx10AudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void Mdajx10AudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void Mdajx10AudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void Mdajx10AudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    // I've added this to avoid people getting screaming feedback
    // when they first compile the plugin, but obviously you don't need to
    // this code if your algorithm already fills all the output channels.
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
        buffer.clear (i, 0, buffer.getNumSamples());

    // This is the place where you'd normally do the guts of your plugin's
    // audio processing...
    for (int channel = 0; channel < getNumInputChannels(); ++channel)
    {
        float* channelData = buffer.getWritePointer (channel);

        // ..do something to the data...
    }
}

//==============================================================================
bool Mdajx10AudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* Mdajx10AudioProcessor::createEditor()
{
    return new Mdajx10AudioProcessorEditor (*this);
}

//==============================================================================
void Mdajx10AudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void Mdajx10AudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new Mdajx10AudioProcessor();
}
